export type {
  DreRow,
  DreMultiPeriodRow,
  DreResponse,
  DreMultiPeriodResponse,
  DreDrillResponse,
  DreNature,
  DreCategoriesResponse,
  DreCategory,
  DreCostCenter,
  DreCostCentersResponse,
  DreReportLine,
  DreReportLinesResponse,
  DreEvolutionPoint,
  DreEvolutionResponse,
} from "@pala-dre/shared"
